# Generated by Django 5.2.10 on 2026-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speeddata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
